server:
  port: 8106

spring:
  application:
    name: inube-registry-service
  security:
    user:
      name: eureka
      password: eureka123

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    wait-time-in-ms-when-sync-empty: 0

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

info:
  app:
    name: Inube Registry Service
    version: 1.0.0

logging:
  level:
    org.springframework.cloud.config: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web.reactive.function.client.ExchangeFunctions: DEBUG